### ISSUE TITLE
GPU Version

### ISSUE THREAD

**Issue by ammadnadeem407** [ARajgor/VTryon-flask-new#1]
Hi, Nice work you have done here. IT works perfectly on CPU, but i have been getting errors running it on GPU.

**Comment by AyushRajgor** [comment]
Can you share more details? Like what the error exactly.. screenshot it.

**Comment by ammadnadeem407** [comment]
Hi, thanks for replying, I have managed to convert it to GPU, before it was generating an error for having two devices for the networks_gmm.py file which was one cpu and one gpu. I am not recieving any error now, but the time it takes to process the files for GPU is more than it was for CPU. I don't know why but it is taking double time for gmm and tom module using gpu.

There was also another issue where gmm module was generating very small warp cloth images for custom dataset. This issue is also resolved when i replaced the background of the cloth images with a white background. Apparently, the gmm module generates more accurate results for cloths with white background.

**Comment by AyushRajgor** [comment]
Actually, python first load on ram on the CPU but for GPU it transfers all the tensors to gpu that's why it takes time.

for the second issue, it requires clear cloth images with clear background. If your query resolve then can I close the issue?

**Comment by ammadnadeem407** [comment]
yes you can close the issue. Thanks for the guidance.
